export default {
    backgroundImage: require('../assets/image/Background.png'),
    googleImage: require('../assets/image/google.png'),
    dashborad: require('../assets/image/dashborad.png'),
    inActiveDashborad: require('../assets/image/inActiveDashborad.png'),
    drivers: require('../assets/image/drivers.png'),
    inActiveDrivers: require('../assets/image/inActiveDrivers.png'),
    resources: require('../assets/image/resources.png'),
    inActiveResources: require('../assets/image/inActiveResources.png'),
    search: require('../assets/image/search.png'),
    inActiveSearch: require('../assets/image/inActiveSearch.png'),
    inActivetalentHub: require('../assets/image/talentHub.png'),
    talentHub: require('../assets/image/activeTalentHub.png'),
    profile: require('../assets/image/Profiledark.png'),
    inActiveProfile: require('../assets/image/Profilelight.png'),
    home: require('../assets/image/Home.png'),
    logout: require('../assets/image/Logout.png'),
    inActiveannouncement: require('../assets/image/announcement.png'),
    announcement: require('../assets/image/Activeannouncement.png'),
    chat: require('../assets/image/chat.png'),
    inquiries: require('../assets/image/Inquiries.png'),
    licenses: require('../assets/image/licenses.png'),
    incidents: require('../assets/image/Incidents.png'),
    driverIcons: require('../assets/image/driversIcon.png')
};